# Generated by Django 3.0.8 on 2020-08-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0014_auto_20200808_1340"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookposition",
            name="month",
            field=models.CharField(blank=True, default="January", max_length=20),
        ),
    ]
