# Generated by Django 3.0.8 on 2020-09-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_auto_20200827_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookposition',
            name='year',
            field=models.IntegerField(blank=True, default=2020),
        ),
    ]
