# Generated by Django 3.0.8 on 2020-09-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0019_bookposition_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookposition",
            name="review",
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
