# Generated by Django 3.0.8 on 2020-10-04 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_auto_20200902_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookposition',
            name='rate',
            field=models.PositiveIntegerField(blank=True, default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='bookposition',
            name='month',
            field=models.CharField(blank=True, default='October', max_length=20),
        ),
    ]
