# Generated by Django 3.0.8 on 2020-10-04 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_auto_20201004_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookposition',
            name='rate',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
