GENRE_CHOICES = (
	("1", "Fantasy"),
	("2", "Adventure"),
	("3", "Romance"),
	("4", "Contemporary"),
	("5", "Dystopian"),
	("6", "Mystery"),
	("7", "Horror"),
	("8", "Thriller"),
	("9", "Paranormal"),
	("10", "Historical fiction"),
	("11", "Science Fiction"),
	("12", "Memoir"),
	("13", "Cooking"),
	("14", "Art"),
	("15", "Personal"),
	("16", "Development"),
	("17", "Motivational"),
	("18", "Health"),
	("19", "History"),
	("20", "Travel"),
	("21", "Guide"),
	("22", "Financials"),
	("23", "Programming"),
	("24", "Families & Relationships"),
	("25", "Humor"),
	("26", "Children's"),
)
