GENRE_CHOICES = (
    ("N/A", "N/A"),
    ("Fantasy", "Fantasy"),
    ("Adventure", "Adventure"),
    ("Romance", "Romance"),
    ("Contemporary", "Contemporary"),
    ("Dystopian", "Dystopian"),
    ("Mystery", "Mystery"),
    ("Horror", "Horror"),
    ("Thriller", "Thriller"),
    ("Paranormal", "Paranormal"),
    ("Historical fiction", "Historical fiction"),
    ("Science Fiction", "Science Fiction"),
    ("Memoir", "Memoir"),
    ("Cooking", "Cooking"),
    ("Art", "Art"),
    ("Personal", "Personal"),
    ("Development", "Development"),
    ("Motivational", "Motivational"),
    ("Health", "Health"),
    ("History", "History"),
    ("Travel", "Travel"),
    ("Guide", "Guide"),
    ("Families & Relationships", "Families & Relationships"),
    ("Humor", "Humor"),
    ("Children's", "Children's"),
    ("Programming", "Programming"),
    ("Financials", "Financials"),
)

MONTH_CHOICES = (
    ("January", "January"),
    ("February", "February"),
    ("March", "March"),
    ("April", "April"),
    ("May", "May"),
    ("June", "June"),
    ("July", "July"),
    ("August", "August"),
    ("September", "September"),
    ("October", "October"),
    ("November", "November"),
    ("December", "December"),
)

STATUS_CHOICES = (
    ("To do", "To do"),
    ("In progress", "In progress"),
    ("Done", "Done"),
)
